//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace subway
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public string ZhanghuId { get; set; }
        public Nullable<int> YuE { get; set; }
        public string Addordec { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<System.DateTime> Modifydate { get; set; }
        public string Laiziyu { get; set; }
        public int Index { get; set; }
    }
}
