//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace subway
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        public string Number { get; set; }
        public Nullable<int> Remain { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Stp { get; set; }
        public string Destination { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Chose_thenum { get; set; }
    }
}
